server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/tp
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    web-application-type: